// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSNamePlusDate
{
    internal sealed partial class Vsix
    {
        public const string Id = "VSNamePlusDate.594f3931-1da9-4fe1-83cf-803dab09a528";
        public const string Name = "VSNamePlusDate";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "ru-RU";
        public const string Version = "1.0";
        public const string Author = "GH.Programmer";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
