// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSNamePlusDate
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VSNamePlusDateString = "32bf848a-bd7e-4f10-9b06-9c9f9feb8e4a";
        public static Guid VSNamePlusDate = new Guid(VSNamePlusDateString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GHMenuGroup = 0x0001;
        public const int NamePlusDateCommand = 0x0100;
    }
}
